TODOLIST_PROJECT/todoList-master/todoApp/urls.py
from django.urls import path
from . import views
app_name = 'todoApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('todo/', views.todoappView, name='todo'),
    path('addTodoItem/',views.addTodoView), 
    path('deleteTodoItem/<int:i>/', views.deleteTodoView), 
] 

TODOLIST_PROJECT/todoList-master/todoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoApp.urls',)),
]

TODOLIST_PROJECT/todoList-master/todoApp/models.py
from django.db import models


# Create your models here.
class TodoListItem(models.Model):
    content = models.TextField() 
    date = models.DateField(auto_now_add=True)

class TodoDone(models.Model):
    done = models.Exists

TODOLIST_PROJECT/todoList-master/todoApp/views.py
from django.shortcuts import render
from .models import TodoListItem 
from .models import TodoDone
from django.http import HttpResponseRedirect 
# Create your views here.
def index(request):
    return render(request, 'index.html')



def todoappView(request):
    all_todo_items = TodoListItem.objects.all()
    all_todo_done = TodoDone.objects.all()
    return render(request, 'todolist.html',  {'all_items':all_todo_items})


def addTodoView(request):
    # x = request.POST.get('todotext')
    new_item = TodoListItem()
    new_item.content = request.POST.get('content')
    new_item.save()
    return HttpResponseRedirect('/todo/') 

def deleteTodoView(request, i):
    y = TodoListItem.objects.get(id= i)
    y.delete()
    return HttpResponseRedirect('/todo/') 

TODOLIST_PROJECT/todoList-master/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>To Do List</title>
</head>
<body style="background-color: burlywood">
    
<div class="container" style="padding-bottom: 80px; bottom: 50px;">
    <div class="row">
      <img src="../static/img/list.jpg" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 600px; height:200px;padding-top: 20px;">
    </div>
    <div class="card text-center" style="margin-top: 200px;">
        <div class="card-body" style="background-color: rgb(255, 238, 241);font-family: Sans;">
          <h5 class="card-title" style="font-family: Sans;">Welcome!! Wanna Add Somethinng</h5>
          <p class="card-text">You can create your own To Do List</p>
          <a href="{% url 'todoApp:todo' %}" class="btn btn-primary">Start Now!</a>
        </div>
        
      </div>
</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

TODOLIST_PROJECT/todoList-master/templates/todolist.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>To-Do List</title>
</head>

<body style="background-color: burlywood">

    <div class="container">

        <h1 style="text-align: center;">CREATE THE LIST</h1>

        <div class="row" style="padding-left: 7cm;">
            <div class="col">

                <div class="row">
                    <form class="form-inline" action="/addTodoItem/" method="post">
                        {% csrf_token %}

                        <div class="row">
                            <div class="col-8">
                                <div class="form-group mx-sm-3 mb-2">
                                    <label for="content" class="sr-only"><b>ADD ITEM</b></label>
                                    <input type="text" class="form-control" name="content" placeholder="Type your item">
                                </div>
                            </div>
                            <div class="col-4" style="margin-top: 25px;">
                                <button type="submit" class="btn btn-primary mb-2">Add Item</button>
                            </div>
                        </div>

                    </form>
                </div>

                <h1 style="padding-left: 4cm;">THINGS TO DO</h1>

                {% for i in all_items %}
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-6">
                        <div class="card  text-white bg-dark mb-3">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-6">
                                        {{i.content}}
                                    </div>
                                    <div class="col-4">
                                        {{i.date}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-2">
                        <form action="/deleteTodoItem/{{i.id}}/" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-trash" viewBox="0 0 16 16">
                                    <path
                                        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                    <path fill-rule="evenodd"
                                        d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                </svg></i>
                            </button>
                        </form>
                    </div>

                    <!-- <div class="col-3">
                        <form action="/doneTodoItem/{{i.id}}/" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-check-lg" viewBox="0 0 16 16">
                                    <path
                                        d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z" />
                                </svg>
                            </button>
                        </form>


                    </div> -->
                    
                </div>
                {% endfor %}

                <h1 style="padding-left: 3cm;">TASKS COMPLETED</h1>

                {% for i in all_items %}
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-6">
                        <div class="card  text-white bg-dark mb-3">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-6">
                                        {{i.content}}
                                    </div>
                                    <div class="col-4">
                                        {{i.date}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>



    </div>


    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>

</html>